chatroom/chatsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
]

chatroom/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.sign_up, name='sign_up'),
    path('signup/code/<int:telegram_id>@<str:username>/', views.index, name='code'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('home/', views.home_page, name='home_page'),
    path('create/', views.create, name='create'),
    path('home/room<str:invite_link>/', views.room(False), name='room'),
    path('home/room<str:invite_link>/ajax', views.room(True), name='room_ajax'),
    path('home/send/', views.send, name='send'),
    path('home/leave/', views.leave, name='leave'),
    path('home/delete-room/', views.delete_room, name='delete_room')
]

chatroom/home/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    telegram_id = models.IntegerField("Telegram ID", null=True, blank=True)
    login_code = models.IntegerField("Login Code", null=True, blank=True)
    passed_login_code = models.BooleanField('Passed Login Code?', null=True, blank=True)


class Room(models.Model):
    name = models.TextField(max_length=200)
    invite_link = models.TextField(max_length=36)
    date_created = models.DateTimeField("date created")
    creator = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Member(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    join_date = models.DateTimeField("join date")
    is_admin = models.BooleanField()
    left = models.BooleanField(default=False)

    def __str__(self):
        return ("(!) " if self.is_admin else "") + self.user.username + " in " + self.room.name


class Message(models.Model):
    text = models.TextField(max_length=4000)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    sender = models.ForeignKey(Member, on_delete=models.PROTECT)
    date = models.DateTimeField("date")
    replied_message = models.ForeignKey('self', on_delete=models.DO_NOTHING, null=True, blank=True)

    def __str__(self):
        return str(self.sender) + '(Message)'

chatroom/home/views.py
import re
import uuid

import requests.exceptions
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, Http404
from django.utils import timezone
from django.shortcuts import render, reverse

from utils import gen_random_code, bot_send_message
from .models import User, Member, Room, Message


def index(request):
    if not request.user.is_authenticated:
        return render(request, 'home/index.html')

    return HttpResponseRedirect(reverse('home:home_page'))


def home_page(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('home:index'))

    context = {'rooms': [member.room for member in Member.objects.filter(user=request.user) if not member.left]}
    return render(request, 'home/home.html', context=context)


def room(is_ajax: bool):
    def view(request, invite_link):
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse('home:index'))

        try:
            r = Room.objects.get(invite_link=invite_link)
        except (Room.DoesNotExist, KeyError):
            messages.error(request, "There is no room with the Invite Link you provided. You can create one here.")
            return HttpResponseRedirect(reverse("home:create"))

        user_rooms = [member.room for member in Member.objects.filter(user=request.user)]
        if r not in user_rooms:
            m = Member(
                user=request.user,
                room=r,
                join_date=timezone.now(),
                is_admin=False,
                left=False
            )
            m.save()
        elif r in user_rooms and (m := Member.objects.get(room=r, user=request.user)).left:
            m.left = False
            m.save()
        preview_rooms = [member.room for member in Member.objects.filter(user=request.user) if not member.left]

        context = {
            'room': r,
            'recent_messages': r.message_set.all()[:200],
            'rooms': preview_rooms,
        }
        return render(request, 'home/chats-ajax.html' if is_ajax else 'home/chats.html', context=context)

    return view


def leave(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('home:index'))
    if not request.POST:
        return Http404()

    try:
        m = Member.objects.get(user=request.user, room__id=request.POST["room-id"])
        m.left = True
        m.save()
        return HttpResponseRedirect(reverse('home:home_page'))
    except (KeyError, Member.DoesNotExist):
        return Http404("This room doesn't exist or you aren't joined.")


def create(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('home:index'))

    if name := request.POST.get('name', None):
        invite_link = str(uuid.uuid4())
        r = Room(
            name=name,
            invite_link=invite_link,
            date_created=timezone.now(),
            creator=request.user
        )
        m = Member(
            user=request.user,
            room=r,
            join_date=timezone.now(),
            is_admin=True
        )
        r.save()
        m.save()
        return HttpResponseRedirect(reverse('home:room', args=(invite_link,)))

    context = {
        'is_creating': True,
        'rooms': [member.room for member in Member.objects.filter(user=request.user)]
    }
    return render(request, 'home/create.html', context=context)


def delete_room(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('home:index'))
    if not request.POST:
        return Http404()
    r = Room.objects.get(id=request.POST['room-id'])
    if r.creator != request.user:
        return Http404("You are not the creator of this room.")

    r.delete()
    return HttpResponseRedirect(reverse('home:index'))


def send(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('home:index'))
    if not request.POST:
        return Http404()

    r = Room.objects.get(invite_link=request.POST['room'])
    sender = Member.objects.get(user=request.user, room=r)
    text = request.POST["message"]

    if reply_id := request.POST.get("reply-id", ""):
        reply = Message.objects.get(id=reply_id)
    else:
        reply = None

    message = Message(sender=sender, text=text, room=r, date=timezone.now(), replied_message=reply)
    message.save()

    return HttpResponseRedirect(reverse('home:room', args=(r.invite_link,)))


def sign_up(request):
    if 'code' not in request.POST:
        username = request.POST['username']
        telegram_id = request.POST['telegram_id']
        if not re.findall('^[a-zA-Z][a-zA-Z0-9_]{4,30}$', username):
            messages.error(request, "Username must only have letters, numbers and underline. It must start with a letter and have at least 5 characters.")
            return HttpResponseRedirect(reverse('home:index'))
        if User.objects.filter(username=username, passed_login_code=True) or User.objects.filter(telegram_id=telegram_id, passed_login_code=True):
            messages.error(request, "A user with this username or Telegram ID already exists.")
            return HttpResponseRedirect(reverse('home:index'))

        try:
            code = gen_random_code()
            bot_send_message(telegram_id, "Your 'Chat Room' Login Code: %s" % code)

            signer = User(telegram_id=telegram_id, username=username, login_code=code, passed_login_code=False)
            signer.set_password(request.POST["password"])
            signer.save()

            messages.info(request, "The Telegram bot sent you the login code.")
            return HttpResponseRedirect(reverse('home:code', args=(signer.telegram_id, signer.username)))
        except requests.exceptions.HTTPError:
            messages.error(request, "An error occurred. Maybe you didn't start the bot.")
            return HttpResponseRedirect(reverse('home:index'))
        except Exception as e:
            messages.error(request, str(e))
            return HttpResponseRedirect(reverse('home:index'))

    else:
        signer = User.objects.get(username=request.POST['username'])
        if signer.passed_login_code:
            return HttpResponseRedirect(reverse("home:index"))
        if not signer.login_code == int(request.POST['code']):
            messages.error(request, 'The code is wrong. Try again.')
            return HttpResponseRedirect(reverse('home:code', args=(signer.telegram_id, signer.username)))
        else:
            signer.passed_login_code = True
            signer.save()
            messages.success(request, 'Created account! Now login with your username and password.')
            return HttpResponseRedirect(reverse('home:index'))


def login_view(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user and (user.passed_login_code or user.is_staff or user.is_superuser):
        login(request, user)
        return HttpResponseRedirect(reverse('home:home_page'))
    else:
        messages.error(request, "You entered a wrong username or password.")
        return HttpResponseRedirect(reverse('home:index'))


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('home:index'))

chatroom/home/templates/home/create.html
{% extends "home/home.html" %}

{% block create_room %}
    <h2>Create a new room and share it with your friends!</h2>
    {% if messages %}
    {% for message in messages %}
        <div title="error" class='p-3 text-danger-emphasis bg-danger-subtle border border-danger-subtle rounded-3 text-break' style="display: inline-block;">
            {{ message }}
        </div>
    <br>
    {% endfor %}
    {% endif %}
    <div title="login" class="border border-3 rounded" style="display: inline-block; padding: 15px; margin: 40px">
                    <form name="create" action="{% url 'home:create' %}" method="post">
                        {% csrf_token %}
                        <h2>Create Room</h2>
                        <hr>
                        <div class="input-group mb-3">
                          <input type="text" required aria-required="true" class="form-control" name="name" id="name" placeholder="Room Name" aria-label="Room Name" aria-describedby="basic-addon1">
                        </div>
                        <button type="submit" value="Create" class="btn btn-primary">Create</button>
                    </form>
                </div>
{% endblock %}

chatroom/home/templates/home/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en" data-bs-theme="dark">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" charset="UTF-8">
    {% if not room %}
        <title>Chat Room</title>
    {% else %}
        <title>{{ room.name }}</title>
    {% endif %}
    <style>
        a {
            color: inherit; /* Use the parent element's color */
            text-decoration: none; /* Remove underline */
        }

        .dark-mode-btn {
            text-align: right;
            margin: 10px;
        }

        #content {
            margin-top: 3cm;
            margin-bottom: 2cm;
            text-align: center;
        }

        #chat-content {
            margin-top: 3cm;
            margin-bottom: 2cm;
        }

        .navbar-title {
            text-align: left;
        }
    </style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <nav class="navbar bg-body-tertiary fixed-top">
    <div class="container-fluid d-flex justify-content-between align-items-center">
        <div class="d-flex align-items-center">
            <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasLeftSidebar" aria-controls="offcanvasLeftSidebar">
                <i class="bi bi-list"></i>
            </button>
            {% if not room %}
                <h5 class="navbar-title mb-0">Chat Room ({{ request.user.username }})</h5>
            {% else %}
                <h5 class="navbar-title mb-0">{{ room.name }} ({{ request.user.username }})</h5>
            {% endif %}
        </div>
        <div class="dark-mode-btn d-flex">
            <button class="btn rounded-circle" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRightSidebar" aria-controls="offcanvasRightSidebar">
                <i class="bi bi-people-fill"></i>
            </button>
            <a href="{% url 'home:logout' %}">
                <button type="button" title="Log Out" class="btn rounded-circle" id="logOut">
                    <i class="bi bi-box-arrow-in-left"></i>
                </button>
            </a>
            <button type="button" class="btn rounded-circle" onclick="changeColorMode()" id="darkMode">
                <i class="bi bi-brightness-high-fill"></i>
            </button>
        </div>
    </div>
</nav>


    {% if is_creating %}
        <div id="content">
            <h2>Create a new room and share it with your friends!</h2>
            {% block create_room %}{% endblock %}
        </div>
    {% elif not room %}
        <div id="content">
            <h2>Click This Button to Open or Create a Room</h2>
        <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasLeftSidebar" aria-controls="offcanvasLeftSidebar">
                <i class="bi bi-list"></i>
        </button>
        </div>
    {% else %}
        <div id="chat-content">
            {% block chats %}{% endblock %}
        </div>
    {% endif %}

    <!-- Left Sidebar -->
    <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasLeftSidebar" aria-labelledby="offcanvasLeftSidebarLabel">
        <div class="offcanvas-header">
            <h2 class="offcanvas-title" id="offcanvasLeftSidebarLabel"><i class="bi bi-chat-left-text-fill"></i> Chat Room</h2>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            <ul class="list-group">
                <li class="list-group-item">
                    <button onclick="window.location.href='{% url 'home:create' %}'" class="btn">
                        <i class="bi bi-plus-circle-fill"></i> Create New Room
                    </button>
                </li>
            </ul>
            <br>
            {% if rooms %}
                <ul class="list-group" id="rooms-sidebar">
                    <li class="list-group-item">
                        <h4><i class="bi bi-houses-fill"></i> {{ request.user.username }}'s Rooms</h4>
                    </li>
                    {% for room in rooms %}
                        <li class="list-group-item">
                            <div class="d-flex w-100 justify-content-between">
                                <button onclick="window.location.href='{% url 'home:room' room.invite_link %}'" class="btn">
                                    {{ room.name }}
                                </button>
                                <div class="d-flex justify-content-between">
                                    <form action="{% url 'home:leave' %}" method="POST" id="leave-form">
                                        {% csrf_token %}
                                        <input type="hidden" name="room-id" value="{{ room.id }}">
                                        <button class="btn" type="submit" title="Leave {{ room.name }}" value="Leave"><i class="bi bi-box-arrow-right"></i></button>
                                    </form>
                                    {% if room.creator == request.user %}
                                    <form action="{% url 'home:delete_room' %}" method="POST">
                                        {% csrf_token %}
                                        <input type="hidden" name="room-id" value="{{ room.id }}">
                                        <button class="btn" type="submit" title="Delete {{ room.name }}" value="Delete"><i class="bi bi-trash"></i></button>
                                    </form>
                                    {% endif %}
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>

    <!-- Right Sidebar -->
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRightSidebar" aria-labelledby="offcanvasRightSidebarLabel">
        <div class="offcanvas-header">
            <h2 class="offcanvas-title" id="offcanvasRightSidebarLabel"><i class="bi bi-people-fill"></i> Members</h2>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            {% if room %}
            <ul class="list-group">
                <li class="list-group-item">
                    <button type="button" onclick="navigator.clipboard.writeText(window.location.href);" class="btn" id="liveToastBtn">
                        <i class="bi bi-share-fill"></i> Share Invite Link
                    </button>
                </li>
            </ul>
            <br>
                <ul class="list-group">
                    <li class="list-group-item">
                        <h4><i class="bi bi-houses-fill"></i> Members of {{ room.name }}</h4>
                    </li>
                    {% for member in room.member_set.all %}
                        <li class="list-group-item">
                            <div class="d-flex w-100 justify-content-between">
                                <p>{{ member.user.username }}{% if room.creator == member.user %} <i class="bi bi-star-fill"></i>{% elif member.is_admin %} <i class="bi bi-star"></i>{% endif %}</p>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>

    {% if room %}
    <div class="toast-container position-fixed bottom-0 end-0 p-3">
      <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header">
          <strong class="me-auto"><i class="bi bi-clipboard"></i> Copied to Clipboard.</strong>
          <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <div class="toast-body">
            The Invite Link of <a href="{% url 'home:room' room.invite_link %}"><b>{{ room.name }}</b></a> has been copied to clipboard.
        </div>
      </div>
    </div>
    {% endif %}


    <!-- Fixed Input and Send Button at the Bottom -->
    {% if room %}
    <nav class="navbar bg-body-tertiary fixed-bottom">
        <div class="container-fluid">
            <form class="d-flex w-100" action="{% url 'home:send' %}" name="send" method="post" id="send-form">
                {% csrf_token %}
                <input required aria-required="true" class="form-control me-2" name="message" id="message-input" type="text" placeholder="Type a message" aria-label="Message">
                <input type="hidden" name="room" id="room" value="{{ room.invite_link }}">
                <input type="hidden" name="reply-id" id="reply-id" value="">
                <button class="btn btn-danger me-2" type="button" hidden="hidden" id="reply-cancel-btn" onclick="cancelReply()"><i class="bi bi-x"></i></button>
                <button class="btn btn-primary" type="submit" value="Send"><i class="bi bi-send-fill"></i></button>
            </form>
        </div>
    </nav>
    {% endif %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'home/theme.js' %}"></script>
    <script type="text/javascript">
        const toastTrigger = document.getElementById('liveToastBtn')
        const toastLiveExample = document.getElementById('liveToast')

        if (toastTrigger) {
          const toastBootstrap = bootstrap.Toast.getOrCreateInstance(toastLiveExample)
          toastTrigger.addEventListener('click', () => {
            toastBootstrap.show()
          })
        }

        document.getElementById("send-form").addEventListener('submit', function (event) {
            event.preventDefault();

            let formData = new FormData(this);
            let xhr = new XMLHttpRequest();

            xhr.open('POST', "{% url 'home:send' %}", true);
            xhr.onreadystatechange = function () {
                if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {
                    document.getElementById("message-input").value = "";
                    document.getElementById("chat-content").innerHTML = xhr.responseText;
                }
            };

            xhr.send(formData);
        })


        {% if room %}
            setInterval(function () {
               let xhr = new XMLHttpRequest();

                xhr.open('GET', '{% url 'home:room_ajax' room.invite_link %}', true);
                xhr.onreadystatechange = function () {
                    if (xhr.readyState === XMLHttpRequest.DONE && xhr.status === 200) {
                        document.getElementById('chat-content').innerHTML = xhr.responseText;
                    }
                };

                xhr.send();
            }, 2000);
        {% endif %}

        function replyToMessage(username, messageId) {
            const input = document.getElementById("message-input");
            const replyMessage = document.getElementById("reply-id");
            const cancelBtn = document.getElementById('reply-cancel-btn');

            input.placeholder = `Reply to ${username}`;
            replyMessage.value = messageId;
            cancelBtn.hidden = false;
        }

        function cancelReply() {
            const input = document.getElementById("message-input");
            const replyMessage = document.getElementById("reply-id");
            const cancelBtn = document.getElementById('reply-cancel-btn');

            input.placeholder = "Type a message";
            replyMessage.value = null;
            cancelBtn.hidden = true;
        }
    </script>
</body>
</html>

chatroom/home/templates/home/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" data-bs-theme="dark">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" charset="UTF-8">
        <title>Chat Room | Sign Up or Login</title>
        <style>
            .main {
                text-align: center;
            }
            .main-title {
                font-size: 70px;
            }
            .dark-mode-btn {
                text-align: right;
                margin: 10px;
            }
        </style>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    </head>
    <body>
        <div title="dark-mode-btn" class="dark-mode-btn">
            <button type="button" class="btn rounded-circle" onclick="changeColorMode()" id="darkMode">
                <i class="bi bi-brightness-high-fill"></i>
            </button>
        </div>
        <div title="main" class="main">
            <div title="title">
                <b class="main-title">Chat Room</b>
                <h1>Create cozy chat rooms and share with your friends!</h1>
            </div>
            {% if messages %}
            {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div title="error" class='p-3 text-danger-emphasis bg-danger-subtle border border-danger-subtle rounded-3 text-break' style="display: inline-block;">
                    {{ message }}
                </div>
                {% else %}
                <div title="success" class='p-3 text-primary-emphasis bg-primary-subtle border border-primary-subtle rounded-3 text-break' style="display: inline-block;">
                    {{ message }}
                </div>
                {% endif %}
                <br>
            {% endfor %}
            {% endif %}
            <div id="forms">
                <div title="signup" class="border border-3 rounded" style="display: inline-block; padding: 15px; margin: 40px">
                    <form name="signup" action="{% url 'home:sign_up' %}" method="post">
                        {% csrf_token %}
                        <h2>Sign Up</h2>
                        <i class="bi bi-exclamation-circle-fill"> Currently, sign up is only possible with a <b>Telegram Account</b>.<br>
                            Remember to <b>/start</b> the <b><a href="https://t.me/ChatRoomHelperBot">@ChatRoomHelperBot</a></b> first.</i>
                        <hr>
                            <div class="input-group mb-3">
                              <span class="input-group-text">ID</span>
                              {% if request.resolver_match.url_name == 'code' %}
                                <input required aria-required="true" type="text" class="form-control" name="telegram_id" id="telegram_id" placeholder="Telegram ID" aria-label="Telegram ID" aria-describedby="basic-addon1" value="{{ telegram_id }}" readonly>
                              {% else %}
                                <input required aria-required="true" type="text" class="form-control" name="telegram_id" id="telegram_id" placeholder="Telegram ID" aria-label="Telegram ID" aria-describedby="basic-addon1">
                              {% endif %}
                            </div>
                            <div class="input-group mb-3">
                              <span class="input-group-text">@</span>
                              {% if request.resolver_match.url_name == 'code' %}
                                <input required aria-required="true" type="text" class="form-control" name="username" id="username" placeholder="Username To Sign Up" aria-label="Username" aria-describedby="basic-addon1" value="{{ username }}" readonly>
                              {% else %}
                                <input required aria-required="true" type="text" class="form-control" name="username" id="username" placeholder="Username To Sign Up" aria-label="Username" aria-describedby="basic-addon1">
                              {% endif %}
                            </div>
                            <div class="input-group mb-3">
                              <span class="input-group-text">*</span>
                              {% if request.resolver_match.url_name == 'code' %}
                                <input required aria-required="true" type="text" class="form-control" name="password" id="password" placeholder="Password" aria-label="Password" aria-describedby="basic-addon1" value="*********" readonly>
                              {% else %}
                                <input required aria-required="true" type="text" class="form-control" name="password" id="password" placeholder="Password" aria-label="Password" aria-describedby="basic-addon1">
                              {% endif %}
                            </div>
                            <hr>
                            {% if request.resolver_match.url_name == 'code' %}
                            <div class="input-group mb-3">
                              <input required aria-required="true" type="text" class="form-control" name="code" id="code" placeholder="Login Code" aria-label="Login Code" aria-describedby="basic-addon1">
                            </div>
                            {% endif %}
                        <button type="submit" value="Signup" class="btn btn-success">Create Account</button>
                        {% if request.resolver_match.url_name == 'code' %}
                            <a href="{% url 'home:index' %}"><button type="button" class="btn btn-warning">Go Back</button></a>
                        {% endif %}
                    </form>
                </div>
                {% if request.resolver_match.url_name == 'index' %}
                <div title="login" class="border border-3 rounded" style="display: inline-block; padding: 15px; margin: 40px">
                    <form name="login" action="{% url 'home:login' %}" method="post">
                        {% csrf_token %}
                        <h2>Login</h2>
                        <i class="bi bi-exclamation-circle-fill"> Login with your registered <b>username</b> and <b>password</b>.</i>
                        <hr>
                        <div class="input-group mb-3">
                          <span class="input-group-text">@</span>
                          <input type="text" required aria-required="true" class="form-control" name="username" id="password" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
                        </div>
                        <div class="input-group mb-3">
                          <span class="input-group-text">*</span>
                          <input type="text" required aria-required="true" class="form-control" name="password" id="password" placeholder="Password" aria-label="Password" aria-describedby="basic-addon1">
                        </div>
                        <button type="submit" value="Login" class="btn btn-primary">Login</button>
                    </form>
                </div>
                {% endif %}
            </div>
            <hr>
            <p>Creator: <a href="https://t.me/PyMamad">@PyMamad</a></p>
        </div>
        <script type="text/javascript" src="{% static 'home/theme.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>